backend_port=9002
everest_config_path=/home/erik/Dokumente/bitbucket/everest_webui/everest-configs/config.yaml
everest_base_config_path=/home/erik/Dokumente/bitbucket/everest_webui/everest-configs/webui_config.yaml
everest_config_overlay_path=/home/erik/Dokumente/bitbucket/everest_webui/everest-configs/user-config/webui_config.yaml
rpc_api_host=127.0.0.1
everest_restart_allowed_states=Unplugged
safety_controller_settings_bin=/home/erik/Dokumente/param_block.bin
safety_controller_settings_yaml=/home/erik/Dokumente/param_block.yaml
