backend_port=9002
everest_config_path=/etc/everest/config.yaml
everest_base_config_path=/etc/everest/everest-ui-config.yaml
everest_config_overlay_path=/etc/everest/user-config/everest-ui-config.yaml
rpc_api_host=127.0.0.1
everest_restart_allowed_states=Unplugged
safety_controller_settings_bin=/home/erik/Dokumente/param_block.bin
safety_controller_settings_yaml=/home/erik/Dokumente/param_block.yaml
